### PR TITLE
Add missing license texts in source files

### LINKED ISSUE #11: GPL license texts are missing in source files
All source/header files under src/ directory does not contain license related text blocks inside them(in the beginning). Sample license text is given below:

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see http://www.gnu.org/licenses/.

### PR DESCRIPTION
**Pull request by anoopcs9**
Fixes #11 

Signed-off-by: Anoop C S anoopcs@redhat.com

### CODE REVIEW

**Comment by craigcabrey** [comment]
I've been meaning to do that, thanks. The only issue is that the original license didn't include the `or any later version` clause.

**Comment by anoopcs9** [comment]
Yo mean COPYING file?

**Comment by anoopcs9** [comment]
As you can see GPLv3 license file COPYING from the git repo is more than enough to take this change in. Please see the description given under "How to Apply These Terms to Your New Programs" section from the following link:

http://www.gnu.org/licenses/gpl-3.0.html

To be more clear see 14th point from the above link.

**Comment by craigcabrey** [comment]
My mistake, I might be thinking of a different project. :+1:

**Pull request merged**
