### PR TITLE
Use FQDN instead of IPv6 while running self-test

### PR DESCRIPTION
**Pull request by anoopcs9**
Signed-off-by: Anoop C S anoopcs@redhat.com

### CODE REVIEW

**Comment by anoopcs9** [comment]
@craigcabrey @nixpanic , What do you think?

**Comment by nixpanic** [comment]
:+1: from me, `::1` should not even be valid I think, similar to how `localhost` and `127.0.0.1` are not

**Comment by craigcabrey** [comment]
The use of `::1` has an interesting history behind it. IIRC, using `127.0.0.1` wouldn't work so I started using `::1` instead. But now that seems to be broken...

Either way, this change seems to fix the issue. Although there seems to be a deeper issue since the loopback addresses _should_ work.

Also, I'm not a bash expert, but should `$(hostname --fqdn)` be wrapped in quotes?

**Comment by craigcabrey** [comment]
@nixpanic loopback addresses aren't valid? I guess that would explain a lot.

**Comment by nixpanic** [comment]
@craigcabrey no, there are not valid, and accepting `::1` was probably an oversight

The `$(....)` notation is the same as using backticks, but more readable

**Comment by craigcabrey** [comment]
FYI @anoopcs9 it looks like the tests for flock are failing for me

**Comment by anoopcs9** [comment]
@craigcabrey , I think I ran all tests successfully on my machine today..Let me check once again.
Thanks.

**Comment by nixpanic** [comment]
https://ci.centos.org/view/Gluster/job/gluster_coreutils/5/console is running now, hopefully we're almost there!

**Comment by craigcabrey** [comment]
Looks like everything passed :+1:. I'll look into why flock was failing on my machine. My laptop runs Arch so that might have something to do with it.

**Comment by anoopcs9** [comment]
@craigcabrey @nixpanic 
Thank you for all your support.

**Pull request merged**
